import type { Metadata } from "next";

import Sidebar from "../../components/sidebar";
import TopNav from "../../components/topnav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div
      style={{
        display: "flex",
        flexDirection: "row",
        backgroundColor: "#f4f8ff",
        height: "100vh",
      }}
    >
      <Sidebar />
      <div
        style={{
          display: "flex",
          flexDirection: "column",
          width: "100%",
          backgroundColor: "#f4f8ff",
        }}
      >
        <TopNav />
        <div
          style={{
            padding: "0px 20px",
            maxHeight: "93vh",
            overflow: "auto",
          }}
        >
          {children}
        </div>
      </div>
    </div>
  );
}
