import type { Metadata } from "next";
import { Inter, Montserrat, Nunito } from "next/font/google";
// import "./globals.css";
import { AuthContextProvider } from "../context/AuthContext";
import { Providers } from "./providers";
import { LocalizationProvider } from "@mui/x-date-pickers";
import { AdapterDayjs } from "@mui/x-date-pickers/AdapterDayjs";

// const inter = Montserrat({ subsets: ["latin"] });
const inter = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    // <Providers>
    // <LocalizationProvider dateAdapter={AdapterDayjs}>
    <AuthContextProvider>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </AuthContextProvider>
    // </LocalizationProvider>
    // </Providers>
  );
}
