import type { Metadata } from "next";
import { Inter, Montserrat, Nunito } from "next/font/google";
// import "./globals.css";
import "@/components/nprogress.css";
import { AuthContextProvider } from "../context/AuthContext";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer, toast } from "react-toastify";
import { AxiosProvider } from "@/context/AxiosContext";

// const inter = Montserrat({ subsets: ["latin"] });
const inter = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    // <Providers>
    // <LocalizationProvider dateAdapter={AdapterDayjs}>
    <AuthContextProvider>
      <AxiosProvider>
        {/* <SWRConfig> */}
          <html lang="en">
            <body className={inter.className}>
              <ToastContainer />
              {children}
            </body>
          </html>
        {/* </SWRConfig> */}
      </AxiosProvider>
    </AuthContextProvider>
    // </LocalizationProvider>
    // </Providers>
  );
}
